### ISSUE TITLE
p1 e p2 em Teoria da Computação estão com a ordem invertida

### ISSUE THREAD

**Issue by arthurgsf** [Marcos-Costa/awesome-ufma#17]
Em relação à forma como o conteúdo está sendo passado atualmente, a p1 deveria ser renomeada como "p2" e vice versa.

**Comment by Marcos-Costa** [comment]
Obrigado por reportar o problema Arthur.  Ele será corrigido.

**Comment by Marcos-Costa** [comment]
Problema corrigido.
